import = ["/Users/adamekka/.config/alacritty/dracula.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 12.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 5000

[window]
decorations = "full"
dynamic_padding = false
opacity = 0.8
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 12
y = 12
